# -*- coding: utf-8 -*-

__author__ = 'Manuel Escriche'

NickNameBook = {
    'Aitor Magán': 'Aitor',
    'Alberto Martín' : 'Alberto',
    'Alessandro Portosa': 'Alessandro',
    'Alex Glikson': 'Alex',
    'Alvaro Alonso': 'Alvaro',
    'Álvaro Arranz' : 'Álvaro',
    'Angelo Giuliana': 'Angelo',
    'Antonio Fuentes Bermejo': 'Antonio',
    'Ari Okkonen' : 'Ari',
    'Atos Spain Tenerife Node Support': "Spain-Tenerife's Team",
    'Backlog Manager': 'Fernando',
    'Barbara Ferraioli': 'Barbara',
    'Berlin Node Helpdesk': 'Berlin Team',
    'Bettan Olivier': 'Olivier',
    'Bitergia forge & tool support' : 'David/Luis',
    'Budapest Node Helpdesk':'Budapest Team',
    'Carlos Ralli Ucendo': 'Carlos',
    'Christian Schlinkmann': 'Christian',
    'Clara Pezuela': 'Clara',
    'Claudio Venezia': 'Claudio',
    'Christophe Azemar': 'Christophe',
    'Crete Node Helpdesk':'Crete Team',
    'Cvetan Stefanovski' : 'Cvetan',
    'Cyril Dangerville': 'Cyril',
    'Daniel Depaoli': 'Daniel',
    'Daniele Pizzolli': 'Daniele',
    'Daniele Santoro': 'Daniele',
    'David Pose': 'David',
    'Davide Dalle Carbonare': 'Davide',
    'Davide Zerbetto': 'Davide',
    'Eran Rom': 'Eran',
    'Ezra Silvera': 'Ezra',
    'Fabio Luciano Mondin': 'Fabio',
    'Federico Cimorelli': 'Federico',
    'Federico Michele Facca': 'Federico',
    'Fermín Galán': 'Fermín',
    'Fernando Lopez': 'Fernando',
    'Francesco Arigliano': 'Francesco',
    'Francisco de la Vega': 'Fran',
    'Francisco Romero': 'Francisco',
    'Franck Le Gall': 'Franck',
    'Genoa Node Support Team':'Genoa Team',
    'German Herrero': 'German',
    'Gilles Privat': 'Gilles',
    'Giuseppe Cossu': 'Giuseppe',
    'Guillermo Jimenez':'Guillermo',
    'Hannover node Support Team': 'Hannover Team',
    'Heike Horstmann': 'Heike',
    'Henar Muñoz': 'Henar',
    'ilknur chulani' : 'Ilknur',
    'Jaime Martin Losa': 'Jaime',
    'Javier Díaz': 'Javier',
    'Javier Soriano': 'Javier',
    'Javier Lucio':'Javier',
    'Jesus Movilla': 'Jesus',
    'Joaquín Iranzo': 'Joaquín',
    'Joaquin Salvachua':'Joaquín',
    'Joel Riga': 'Joel',
    'Jonne Väisänen': 'Jonne',
    'Jose Manuel Cantera': 'Jose Manuel',
    'José Ignacio Carretero Guarde': 'José Ignacio',
    'Juan Bareño': 'Juan',
    'Juanjo Hierro': 'Juanjo',
    'Juha Hyvärinen' : 'Juha',
    'J-P Viuhkola': 'Juho-Pekka',
    'Karaboga, Burak': 'Burak',
    'Karlskrona Node Helpdesk': 'Karlskrona Team',
    'Katarzyna Di Meo':'Katarzyna',
    'Kenneth Nagin': 'Kenneth',
    'Lannion Node Helpdesk': 'Lannion Team',
    'Laura Pucci': 'Laura',
    'Laurent ARTUSIO': 'Laurent',
    'Leandro Guillén': 'Leandro',
    'Lorenzo Eccher': 'Lorenzo',
    'Luis López Fernández': 'Luis',
    'Manuel Escriche': 'Manuel',
    'Marco Terrinoni': 'Marco',
    'Malena Donato Cohen': 'Malena',
    'Mauro Pecetti': 'Mauro',
    'Mexico Node Support' : 'Mexico Team',
    'Miguel Carrillo' : 'Miguel',
    'Miguel Jiménez': 'Miguel',
    'Nuria de Lama Sanchez':'Nuria',
    'OKFN CKAN team': 'Jo',
    'Ozdemir, Omer Faruk': 'Omer',
    'Pablo Fernandez Moniz': 'Pablo',
    'Pablo Honrubia': 'Pablo',
    'Pablo Rodríguez Archilla': 'Pablo',
    'Pascal Bisson' : 'Pascal',
    'Pasquale Andriani' : 'Pasquale',
    'Pasquale Vitale': 'Pasquale',
    'Pedro Luis Chas Alonso': 'Pedro',
    'Pedro Verdugo': 'Pedro',
    'Pietropaolo Alfonso': 'Alfonso',
    'PiraeusN Node Helpdesk': 'PiraeusN Team',
    'PiraeusU Node Helpdesk': 'PireausU Team',
    'Poznan Node Helpdesk': 'Poznan Team',
    'Prague Node Helpdesk' : 'Prague Team',
    'Radoslaw Adamkiewicz': 'Radoslaw',
    'Roberto Antonini': 'Roberto',
    'Santiago Martinez García': 'Santiago',
    'Sao Paolo Node Support Team': "Sao Paolo's Team",
    'Sergio Garcia Gomez': 'Sergio',
    'Silvio Cretti': 'Silvio',
    'Sophia Antipolis Node Helpdesk': 'Sophia Team',
    'Spain Node Support Team': 'Spain Team',
    'Stefan Gessler': 'Stefan',
    'Stefano De Panfilis': 'Stefano',
    'Stephan Neuhaus': 'Stephan',
    'Susanna Varho': 'Susana',
    'Tarek Elsaleh' : 'Tarek',
    'Thomas Michael Bohnert': 'Thomas',
    'Trento Node Team': "Trento's Team",
    'Torsten Spieldenner': 'Torsten',
    'Uri Shani': 'Uri',
    'Vicenza Node Support': "Vicenza's Team",
    'Volos Node Helpdesk': 'Volos Team',
    'Yosef Moatti': 'Yosef',
    'Zurich Node Helpdesk':'Zurich Team',
    'ZurichS Node Support':'Zurich-S Team'
}